from typing import Any

from osgeo import ogr, osr
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProcessingContext,
    QgsProcessingFeedback,
    QgsProcessingParameterFileDestination,
)


class GenerateGeopackageAlgorithm(QgsProcessingAlgorithm):
    """Creates an empty Raster Caster GeoPackage (SRID 28992).

    Tables created:
        surface          – Polygon
        auxiliary_line   – MultiLineStringZ
        elevation_point  – Point  (with a second PointZ column ``geom_3d``)
    """

    OUTPUT = "OUTPUT"

    def name(self) -> str:
        return "generate_geopackage"

    def displayName(self) -> str:
        return "Generate GeoPackage"

    def group(self) -> str:
        return "Data Management"

    def groupId(self) -> str:
        return "data_management"

    def shortHelpString(self) -> str:
        return (
            "Generates an empty Raster Caster GeoPackage with tables: "
            "surface, auxiliary_line, and elevation_point."
        )

    def createInstance(self) -> "GenerateGeopackageAlgorithm":
        return GenerateGeopackageAlgorithm()

    def initAlgorithm(self, config: dict[str, Any] | None = None) -> None:
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                "Output GeoPackage",
                fileFilter="GeoPackage files (*.gpkg)",
            )
        )

    def processAlgorithm(
        self,
        parameters: dict[str, Any],
        context: QgsProcessingContext,
        feedback: QgsProcessingFeedback,
    ) -> dict[str, str]:
        output_path = self.parameterAsString(parameters, self.OUTPUT, context)

        srs = osr.SpatialReference()
        srs.ImportFromEPSG(28992)

        driver = ogr.GetDriverByName("GPKG")
        ds = driver.CreateDataSource(output_path)

        self.create_aux_line(ds, srs)
        self.create_surface(ds, srs)
        self.create_el_point(ds, srs)

        ds = None  # flush and close

        return {self.OUTPUT: output_path}

    # ------------------------------------------------------------------
    # Table definitions
    # ------------------------------------------------------------------

    @staticmethod
    def create_surface(ds: ogr.DataSource, srs: osr.SpatialReference) -> None:
        lyr = ds.CreateLayer("surface", srs, ogr.wkbPolygon)

        fld = ogr.FieldDefn("definition", ogr.OFTString)
        fld.SetDefault("'NULL'")
        lyr.CreateField(fld)
        lyr.CreateField(ogr.FieldDefn("definition_type", ogr.OFTString))
        lyr.CreateField(ogr.FieldDefn("comment", ogr.OFTString))

        for i in range(1, 7):
            lyr.CreateField(ogr.FieldDefn(f"aux_{i}", ogr.OFTInteger))
        for i in range(1, 7):
            lyr.CreateField(ogr.FieldDefn(f"param_{i}", ogr.OFTReal))

    @staticmethod
    def create_aux_line(ds: ogr.DataSource, srs: osr.SpatialReference) -> None:
        lyr = ds.CreateLayer("auxiliary_line", srs, ogr.wkbMultiLineString25D)

        lyr.CreateField(ogr.FieldDefn("comment", ogr.OFTString))

        fld = ogr.FieldDefn("autogenerated", ogr.OFTInteger)
        fld.SetSubType(ogr.OFSTBoolean)
        fld.SetDefault("0")
        lyr.CreateField(fld)

    @staticmethod
    def create_el_point(ds: ogr.DataSource, srs: osr.SpatialReference) -> None:
        lyr = ds.CreateLayer("elevation_point", srs, ogr.wkbPoint)

        lyr.CreateField(ogr.FieldDefn("comment", ogr.OFTString))
        lyr.CreateField(ogr.FieldDefn("elevation", ogr.OFTReal))

        fld = ogr.FieldDefn("in_polygon_only", ogr.OFTInteger)
        fld.SetSubType(ogr.OFSTBoolean)
        fld.SetDefault("0")
        lyr.CreateField(fld)

        geom_fld = ogr.GeomFieldDefn("geom_3d", ogr.wkbPoint25D)
        geom_fld.SetSpatialRef(srs)
        lyr.CreateGeomField(geom_fld)
